version: "3"
services:
  xrce:
    build: ./xrce_dds_agent
    image: xrce
    network_mode: host

    #ports:
    #  - "8888:8888"
    #volumes:
    #  - .:/code
  px4:
    build: ./px4
    image: px4
    network_mode: host
    ipc: host
    pid: host
    
    stdin_open: true
    tty: true
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      #PX4_SIM_HOST_ADDR: 192.168.0.2
      NV_PRIME_RENDER_OFFLOAD: 1
      GLX_VENDOR_LIBRARY_NAME: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority

    runtime: nvidia 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  ros:
    build: ./ros
    image: ros
    network_mode: host
    ipc: host
    pid: host
    
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      NV_PRIME_RENDER_OFFLOAD: 1
      GLX_VENDOR_LIBRARY_NAME: nvidia
    
    runtime: nvidia 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
    volumes:
      - ./ros/ros_ws:/ros_ws

volumes:
  ros_ws :