version: "3"
services:
  xrce:
    build: ./xrce_dds_agent
    image: xrce
    network_mode: host
    #ports:
    #  - "8888:8888"
    #volumes:
    #  - .:/code
  px4:
    build: ./px4
    image: px4
    network_mode: host
    environment:
      DISPLAY: $DISPLAY
      PX4_SIM_HOST_ADDR: 172.17.128.1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
  ros:
    build: ./ros
    image: ros
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./ros/ros_ws:/ros_ws

volumes:
  ros_ws :